"""empty message

Revision ID: 4f3190a03f7e
Revises: 81a527ecaaf5
Create Date: 2023-09-25 20:53:43.411720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f3190a03f7e'
down_revision: Union[str, None] = '81a527ecaaf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Orders_creation_time', table_name='Orders')
    op.drop_column('Orders', 'creation_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Orders', sa.Column('creation_time', sa.DATETIME(), nullable=True))
    op.create_index('ix_Orders_creation_time', 'Orders', ['creation_time'], unique=False)
    # ### end Alembic commands ###
