"""empty message

Revision ID: 81a527ecaaf5
Revises: 
Create Date: 2023-09-25 20:51:04.758750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81a527ecaaf5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=50), nullable=True),
    sa.Column('coinbase_id', sa.String(length=50), nullable=True),
    sa.Column('transaction_type', sa.String(length=10), nullable=True),
    sa.Column('product', sa.String(length=10), nullable=True),
    sa.Column('balanceBeforeTransaction', sa.String(length=20), nullable=True),
    sa.Column('price', sa.String(length=10), nullable=True),
    sa.Column('amount', sa.String(length=20), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('time_of_order', sa.DateTime(), nullable=True),
    sa.Column('additionalInfo', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Orders_creation_time'), 'Orders', ['creation_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Orders_creation_time'), table_name='Orders')
    op.drop_table('Orders')
    # ### end Alembic commands ###
