"""empty message

Revision ID: f0169b4299d5
Revises: 4f3190a03f7e
Create Date: 2023-09-26 20:03:46.033631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0169b4299d5'
down_revision: Union[str, None] = '4f3190a03f7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Orders', sa.Column('base_currency_balance_before_order', sa.String(length=10), nullable=True))
    op.add_column('Orders', sa.Column('quote_currency_balance_before_order', sa.String(length=10), nullable=True))
    op.add_column('Orders', sa.Column('base_currency_balance_after_order', sa.String(length=10), nullable=True))
    op.add_column('Orders', sa.Column('quote_currency_balance_after_order', sa.String(length=10), nullable=True))
    op.add_column('Orders', sa.Column('additional_info', sa.Text(), nullable=True))
    op.drop_column('Orders', 'additionalInfo')
    op.drop_column('Orders', 'balanceBeforeTransaction')
    op.drop_column('Orders', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Orders', sa.Column('amount', sa.VARCHAR(length=20), nullable=True))
    op.add_column('Orders', sa.Column('balanceBeforeTransaction', sa.VARCHAR(length=20), nullable=True))
    op.add_column('Orders', sa.Column('additionalInfo', sa.TEXT(), nullable=True))
    op.drop_column('Orders', 'additional_info')
    op.drop_column('Orders', 'quote_currency_balance_after_order')
    op.drop_column('Orders', 'base_currency_balance_after_order')
    op.drop_column('Orders', 'quote_currency_balance_before_order')
    op.drop_column('Orders', 'base_currency_balance_before_order')
    # ### end Alembic commands ###
